"""Domain-specific catalogs and selection helpers."""

from ai4s_agent.domains.model_registry import DomainModelRegistry
from ai4s_agent.domains.oled_baseline_backend import (
    OledBaselineBackendKind,
    run_oled_baseline_backend,
)
from ai4s_agent.domains.oled_baseline_loop import (
    OledAblationReport,
    OledAblationReportEntry,
    OledBaselineAblationKind,
    OledBaselineExperimentArm,
    OledBaselineExperimentSpec,
    OledBaselineFeatureView,
    build_oled_baseline_experiment_spec,
    initialize_oled_ablation_report,
)
from ai4s_agent.domains.oled_contracts import (
    DEFAULT_OLED_REPRESENTATION_CONTRACT,
    OledCausalLayer,
    RepresentationClaim,
    RepresentationContract,
    RepresentationContractFinding,
    RepresentationContractReport,
)
from ai4s_agent.domains.oled_feature_materialization import (
    OledFeatureMaterializationRow,
    OledFeatureMaterializationTable,
    materialize_oled_baseline_feature_table,
    materialize_oled_baseline_feature_tables,
    write_oled_feature_table_jsonl,
)
from ai4s_agent.domains.oled_gold_validation import (
    OledGoldDatasetRecord,
    OledGoldValidationFinding,
    OledGoldValidationReport,
    validate_oled_gold_dataset,
)
from ai4s_agent.domains.oled_layered_schema import (
    OledConfidenceAssessment,
    OledConfounderFlags,
    OledConfounderTag,
    OledConfounderType,
    OledDeviceLayer,
    OledEvidenceSource,
    OledEvidenceType,
    OledInteractionLayer,
    OledLayeredCanonicalObservation,
    OledLayeredRecord,
    OledLayeredSchemaFinding,
    OledLayeredSchemaReport,
    OledMeasurementCondition,
    OledMeasurementLayer,
    OledMolecularLayer,
    OledPropertyObservation,
)
from ai4s_agent.domains.oled_property_ontology import (
    DEFAULT_OLED_PROPERTY_ONTOLOGY,
    OledPropertyDefinition,
    OledPropertyOntology,
    OledPropertyOntologyFinding,
    OledPropertyOntologyReport,
    OledPropertyValueConstraint,
)
from ai4s_agent.domains.oled_property_taxonomy import (
    DEFAULT_OLED_PROPERTY_TAXONOMY,
    OledPropertyTaxonomy,
    OledPropertyTaxonomyMatch,
)
from ai4s_agent.domains.oled_split_leakage import (
    OledLeakageGroupKind,
    OledLeakageGuardSplitPlan,
    OledSplitAssignment,
    OledSplitLeakageFinding,
    OledSplitLeakageReport,
    build_oled_leakage_guard_split,
    validate_oled_split_leakage,
)
from ai4s_agent.domains.oled_units import (
    OledUnitNormalizationResult,
    OledUnitNormalizationStatus,
    normalize_oled_condition_field,
    normalize_oled_property_unit,
)

__all__ = [
    "DEFAULT_OLED_PROPERTY_ONTOLOGY",
    "DEFAULT_OLED_PROPERTY_TAXONOMY",
    "DEFAULT_OLED_REPRESENTATION_CONTRACT",
    "DomainModelRegistry",
    "OledAblationReport",
    "OledAblationReportEntry",
    "OledBaselineAblationKind",
    "OledBaselineBackendKind",
    "OledBaselineExperimentArm",
    "OledBaselineExperimentSpec",
    "OledBaselineFeatureView",
    "OledCausalLayer",
    "OledConfidenceAssessment",
    "OledConfounderFlags",
    "OledConfounderTag",
    "OledConfounderType",
    "OledDeviceLayer",
    "OledEvidenceSource",
    "OledEvidenceType",
    "OledFeatureMaterializationRow",
    "OledFeatureMaterializationTable",
    "OledGoldDatasetRecord",
    "OledGoldValidationFinding",
    "OledGoldValidationReport",
    "OledInteractionLayer",
    "OledLeakageGroupKind",
    "OledLeakageGuardSplitPlan",
    "OledLayeredCanonicalObservation",
    "OledLayeredRecord",
    "OledLayeredSchemaFinding",
    "OledLayeredSchemaReport",
    "OledMeasurementCondition",
    "OledMeasurementLayer",
    "OledMolecularLayer",
    "OledPropertyDefinition",
    "OledPropertyOntology",
    "OledPropertyOntologyFinding",
    "OledPropertyOntologyReport",
    "OledPropertyObservation",
    "OledPropertyTaxonomy",
    "OledPropertyTaxonomyMatch",
    "OledPropertyValueConstraint",
    "OledSplitAssignment",
    "OledSplitLeakageFinding",
    "OledSplitLeakageReport",
    "OledUnitNormalizationResult",
    "OledUnitNormalizationStatus",
    "RepresentationClaim",
    "RepresentationContract",
    "RepresentationContractFinding",
    "RepresentationContractReport",
    "build_oled_baseline_experiment_spec",
    "build_oled_leakage_guard_split",
    "initialize_oled_ablation_report",
    "materialize_oled_baseline_feature_table",
    "materialize_oled_baseline_feature_tables",
    "normalize_oled_condition_field",
    "normalize_oled_property_unit",
    "run_oled_baseline_backend",
    "validate_oled_gold_dataset",
    "validate_oled_split_leakage",
    "write_oled_feature_table_jsonl",
]
