"""CORE-03 compliant, cache-first literature acquisition."""

from .cache import AcquisitionCache, CacheEntry, CachedResponse
from .errors import (
    AcquisitionCacheError,
    AcquisitionConfigurationError,
    AcquisitionError,
    AcquisitionIntegrityError,
    AcquisitionPolicyError,
    AcquisitionTransportError,
    AcquisitionTimeoutError,
    CredentialLeakError,
)
from .models import (
    ACCEPTED_MEDIA_TYPES,
    AcquisitionConfig,
    AcquisitionProvenance,
    AcquisitionStatus,
    ArtifactClass,
    ContentFamily,
    EphemeralAccessMaterial,
    MetadataRecord,
    ProviderClass,
    ProviderConfig,
    ProviderRoute,
    RetryPolicy,
    SourceCandidate,
)
from .policy import (
    CanonicalURL,
    canonicalize_url,
    classify_route,
    content_family_for_media_type,
    normalize_doi,
    normalize_result_limit,
    normalize_search_query,
    sanitize_url,
    validate_resolved_addresses,
)
from .providers import (
    ConfiguredFullTextFetcher,
    CrossrefProvider,
    FullTextFetcher,
    MetadataProvider,
    OpenAccessResolver,
    OpenAlexProvider,
    ProviderRequest,
    UnpaywallResolver,
)
from .service import (
    AccessProfileResolver,
    AcquisitionService,
    EmptyAccessProfileResolver,
    StaticAccessProfileResolver,
)
from .tools import acquisition_tool_specs, register_acquisition_tools
from .transport import DNSResolver, NetworkResponse, NetworkTransport, SafeNetworkTransport, SystemDNSResolver

__all__ = [
    "ACCEPTED_MEDIA_TYPES",
    "AccessProfileResolver",
    "AcquisitionCache",
    "AcquisitionCacheError",
    "AcquisitionConfig",
    "AcquisitionConfigurationError",
    "AcquisitionError",
    "AcquisitionIntegrityError",
    "AcquisitionPolicyError",
    "AcquisitionProvenance",
    "AcquisitionService",
    "AcquisitionStatus",
    "AcquisitionTransportError",
    "AcquisitionTimeoutError",
    "ArtifactClass",
    "CacheEntry",
    "CanonicalURL",
    "CachedResponse",
    "ContentFamily",
    "ConfiguredFullTextFetcher",
    "CredentialLeakError",
    "CrossrefProvider",
    "FullTextFetcher",
    "DNSResolver",
    "EmptyAccessProfileResolver",
    "EphemeralAccessMaterial",
    "MetadataProvider",
    "MetadataRecord",
    "NetworkResponse",
    "NetworkTransport",
    "OpenAccessResolver",
    "OpenAlexProvider",
    "ProviderClass",
    "ProviderConfig",
    "ProviderRequest",
    "ProviderRoute",
    "RetryPolicy",
    "SafeNetworkTransport",
    "SourceCandidate",
    "StaticAccessProfileResolver",
    "SystemDNSResolver",
    "UnpaywallResolver",
    "acquisition_tool_specs",
    "canonicalize_url",
    "classify_route",
    "content_family_for_media_type",
    "normalize_doi",
    "normalize_result_limit",
    "normalize_search_query",
    "register_acquisition_tools",
    "sanitize_url",
    "validate_resolved_addresses",
]
